# Generated by Django 3.2.13 on 2022-05-19 04:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='second_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
